/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32f4xx.h>

#include "FreeRTOS.h"
#include "task.h"

#include <stdint.h>
#include <stdio.h>

#include "gpio_driver_hal.h"

#define STACK_SIZE 200

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif


/*Definicion de variables del sistema*/
uint32_t SystemCoreClock = 16000000;

/*Perifericos del sistema*/
GPIO_Handler_t led_state_Handler = {0};

/*Cabeceras de las funciones del programa*/
void vTask_blink_led( void * pvParameters );
void vTaskTwo( void * pvParameters );

void initSystem(void);

int main(void)
{
	/*Activamos la unidad de punto flotante (FPU)*/
	SCB->CPACR  |= (0xF << 20);

	/*Activación del contador de Ticks*/
	DWT->CTRL    |= (1 << 0);

	/*inicializacion de los perifericos del sistema*/
	initSystem();

	/*Necesario para el SEGGER*/
	vInitPrioGroupValue();
	/* Primero configuramos */
	SEGGER_SYSVIEW_Conf();
	/* Despues activamos el sistema */
	SEGGER_SYSVIEW_Start();

	BaseType_t xReturned;
	TaskHandle_t xHandleTask_blinky_led = NULL;
	TaskHandle_t xHandleTask2 = NULL;

	xReturned = xTaskCreate(
			vTask_blink_led,                         /*Function that implements the task*/
			"Task-Blinky",                         /*Text name for the task*/
			STACK_SIZE,                       /*stack size in words, not bytes*/
			"Blinky",  /*Parameter passed into the task*/
			2,                                /*Priority at which the task is created*/
			&xHandleTask_blinky_led );

	configASSERT(xReturned == pdPASS);

	xReturned = xTaskCreate(
			vTaskTwo,                         /*Function that implements the task*/
			"Task-2",                         /*Text name for the task*/
			STACK_SIZE,                       /*stack size in words, not bytes*/
			"Hola Mundo desde la Tarea - 2",  /*Parameter passed into the task*/
			2,                                /*Priority at which the task is created*/
			&xHandleTask2);

	configASSERT(xReturned == pdPASS);

	/*Start the created tasks running*/
	vTaskStartScheduler();


    /* Loop forever */
	while(1){
		/*Si llegamos aca, es que algo salió mal*/

	}
}// fin del main

/*Funcion para inicializar todo el hardware del sistema*/
void initSystem(void){
	/*Configuramos el Led de estado*/
	led_state_Handler.pGPIOx = GPIOA;
	led_state_Handler.pinConfig.GPIO_PinNumber = PIN_5;
	led_state_Handler.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	led_state_Handler.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	led_state_Handler.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_LOW;
	led_state_Handler.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	gpio_Config(&led_state_Handler);
	gpio_WritePin(&led_state_Handler,RESET);


}

/*Funcion que gobierna a la tarea 1*/
void vTask_blink_led(void*pvParameters)
{
	while(1)
	{
		/*Task code goes here*/
//		printf("%s\n",(char*)pvParameters);
		gpio_TooglePin(&led_state_Handler);
		vTaskDelay(pdMS_TO_TICKS(250));
		//taskYIELD();
	}
}

/*Funcion que gobierna a la tarea 2*/
void vTaskTwo(void*pvParameters){
	while(1)
	{
		/*Task code goes here*/
		printf("%s\n",(char*)pvParameters);
		vTaskDelay(pdMS_TO_TICKS(10));
	    //taskYIELD();

	}

}




