/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32f4xx.h>

#include "FreeRTOS.h"
#include "task.h"

#include <stdint.h>
#include <stdio.h>

#define STACK_SIZE 200



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



/*Definicion de variables del sistema*/
uint32_t SystemCoreClock = 16000000;

int main(void)
{
	SCB->CPACR  |= (0xF << 20);
	DWT->CTRL    |= (1 << 0);

	/*Necesario para el SEGGER*/
	vInitPrioGroupValue();
	/* Primero configuramos */
	SEGGER_SYSVIEW_Conf();
	/* Despues activamos el sistema */
	SEGGER_SYSVIEW_Start();


    /* Loop forever */
	while(1){

	}
}
